version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: $HASH_DB
      MYSQL_USER: $HASH_USER
      MYSQL_PASSWORD: $HASH_PASS
