version: '3.8'
services:
  hashtopolis:
    container_name: hashtopolis
    build: .
    restart: always
    volumes:
      ##
      # !!! CAREFUL, importing from here will delete whatever file is in this folder !!!
      - ./src/import/:/var/www/html/import/:Z
      ##
      - ./src/files/:/var/www/html/files/:Z
      - ./data/conf.php:/var/www/html/inc/conf.php:Z
    depends_on:
      - db
    ports:
      - 8080:80
    cap_drop:
      - ALL
    cap_add:
      # used to change files since non-priv user
      - CHOWN
      # used for the gosu binary
      - CAP_SETGID
      - CAP_SETUID
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: $HASH_DB
      MYSQL_USER: $HASH_USER
      MYSQL_PASSWORD: $HASH_PASS
    cap_drop:
      - ALL
    cap_add:
      # used to change files since non-priv user
      - CHOWN
      # used because container uses find command
      - CAP_DAC_READ_SEARCH
      # used for the gosu binary
      - CAP_SETGID
      - CAP_SETUID
