version: '3.8'
services:
  hashtopolis:
    container_name: php-apache
    build: .
    restart: always
    volumes:
      - ./src/import/:/var/www/html/import/:ro
      - ./data/conf.php:/var/www/html/inc/conf.php
    depends_on:
      - db
    ports:
      - 8080:80
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - CAP_SETGID
      - CAP_SETUID
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: $HASH_DB
      MYSQL_USER: $HASH_USER
      MYSQL_PASSWORD: $HASH_PASS
    cap_drop:
      - ALL
    cap_add:
      - CAP_SETGID
      - CAP_SETUID
      - CHOWN
      - CAP_DAC_READ_SEARCH
